[package]
name = "orbita"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
mlua = {version = "0.10.2", features = ["vendored", "luajit"]}

[[bin]]
name = "orbita"
path = "src/main.rs"
